// Post-build step: take dist/index.html and emit dist/remix.html for upload to
// the Remix (remix.gg) Native App platform. Remix scans the HTML and rejects
// any external resource not on its allowlist (remix.gg, vercel-storage,
// cdn.jsdelivr.net/npm, cdnjs). It flagged:
//   - https://telegram.org/js/telegram-web-app.js        (Telegram SDK script)
//   - https://treasurequest-tg.bizarrebeasts.io/...png   (og/twitter preview image)
//   - https://treasurequest-tg.bizarrebeasts.io/         (og:url)
//
// Those are marked with data-remix-strip in index.html and removed here. The
// Farcade SDK + Phaser (cdn.jsdelivr.net) and game assets (vercel-storage) are
// allowlisted and kept. The Telegram call sites in the game guard on
// window.Telegram?.WebApp?.initData and no-op when the script is absent, so
// removing it is safe on Remix.

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const distDir = path.resolve(__dirname, '../dist');
const sourceFile = path.join(distDir, 'index.html');
const outputFile = path.join(distDir, 'remix.html');

if (!fs.existsSync(sourceFile)) {
  console.error(`build-remix: ${sourceFile} not found — run the main build first.`);
  process.exit(1);
}

const original = fs.readFileSync(sourceFile, 'utf8');

// Strip <script ... data-remix-strip ...>...</script> (Telegram SDK) and
// self-closing <meta ... data-remix-strip ... /> (social-preview tags pointing
// at the unapproved bizarrebeasts.io domain). The attribute survives HTML
// minification, unlike comments.
const scriptRe = /<script\b[^>]*\bdata-remix-strip\b[^>]*>[\s\S]*?<\/script>\s*/gi;
const metaRe = /<meta\b[^>]*\bdata-remix-strip\b[^>]*\/?>\s*/gi;
let stripped = original.replace(scriptRe, '').replace(metaRe, '');

if (stripped === original) {
  console.error('build-remix: no data-remix-strip elements found in dist/index.html.');
  console.error('  Either the attributes were never added to source, or the build pipeline');
  console.error('  is rewriting them. Aborting to avoid shipping unapproved external');
  console.error('  resources that Remix will reject.');
  process.exit(1);
}

// Neutralize Telegram share/deep-link URLs (https://t.me/...) baked into the
// bundled JS as string literals. That code is Telegram-only and never runs on
// Remix, but Remix's static scanner still flags the literal as an external
// resource. Rewriting the scheme makes it a non-URL token (no behavior change
// on Remix; the dead code path is unreachable there anyway).
stripped = stripped.replace(/https:\/\/t\.me\//g, 'tg-disabled:/');

// Guard: the Remix build must not reference any domain Remix has rejected.
const banned = ['treasurequest-tg.bizarrebeasts.io', 'telegram.org', 't.me/', 'googletagmanager.com'];
const stillPresent = banned.filter((d) => stripped.includes(d));
if (stillPresent.length) {
  console.error(`build-remix: output still references unapproved resource(s): ${stillPresent.join(', ')}.`);
  console.error('  Mark the offending tag with data-remix-strip (HTML) or extend the URL');
  console.error('  rewrite above (bundled JS). Aborting.');
  process.exit(1);
}

const banner = `<!-- Remix (remix.gg) build — generated by scripts/build-remix.js. Do not edit by hand; rerun \`npm run build\`. -->\n`;
fs.writeFileSync(outputFile, banner + stripped);

const inSize = (fs.statSync(sourceFile).size / 1024).toFixed(1);
const outSize = (fs.statSync(outputFile).size / 1024).toFixed(1);
console.log(`build-remix: wrote ${outputFile} (${inSize}KB -> ${outSize}KB)`);
