// Post-build step: take dist/index.html and emit dist/kids.html with the
// third-party tracker scripts removed. The kids.html is hosted on
// kids.bizarrebeasts.io (same origin as that site) so COPPA-aged players can
// play without GA, Telegram, or Farcade SDKs leaking IP/UA to third parties.
//
// Tracking call sites in the game already guard on the presence of these
// globals (window.gtag, window.FarcadeSDK, window.Telegram.WebApp.initData)
// and no-op when absent — so removing the script tags is sufficient. Phaser
// is kept (it's the game engine, not a tracker).

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const distDir = path.resolve(__dirname, '../dist');
const sourceFile = path.join(distDir, 'index.html');
const outputFile = path.join(distDir, 'kids.html');

if (!fs.existsSync(sourceFile)) {
  console.error(`build-kids: ${sourceFile} not found — run the main build first.`);
  process.exit(1);
}

const original = fs.readFileSync(sourceFile, 'utf8');

// Remove any <script ... data-kids-strip ...>...</script>. Attribute survives
// HTML minification (unlike HTML comments). Matches both src and inline scripts.
const scriptRe = /<script\b[^>]*\bdata-kids-strip\b[^>]*>[\s\S]*?<\/script>\s*/gi;
const stripped = original.replace(scriptRe, '');

if (stripped === original) {
  console.error('build-kids: no data-kids-strip script tags found in dist/index.html.');
  console.error('  Either the attribute was never added to source scripts, or the build');
  console.error('  pipeline is rewriting the attribute. Aborting to avoid shipping a');
  console.error('  non-COPPA build.');
  process.exit(1);
}

const banner = `<!-- COPPA-safe build for kids.bizarrebeasts.io — generated by scripts/build-kids.js. Do not edit by hand; rerun \`npm run build\`. -->\n`;
fs.writeFileSync(outputFile, banner + stripped);

const inSize = (fs.statSync(sourceFile).size / 1024).toFixed(1);
const outSize = (fs.statSync(outputFile).size / 1024).toFixed(1);
console.log(`build-kids: wrote ${outputFile} (${inSize}KB -> ${outSize}KB)`);
